### ISSUE TITLE
Please resolve error in this file

### ISSUE THREAD

**Issue by OsamaNajeeb** [OsamaNajeeb/SQAStudent_20F20753#3]
Can you find the errors and resolve it, what's wrong within line 14

**Comment by drakewilliam** [comment]
Found two errors
You didn't include int within line 12, so it will also accept strings
and finally in line 14 you have to use Market_Range not Market

**Comment by OsamaNajeeb** [comment]
Another error in line 25

**Comment by drakewilliam** [comment]
Yes, you didn't add indexes after Market_List, so it's actually Market_List[EYE]
I think the program is functional

**Comment by OsamaNajeeb** [comment]
Thanks
